### PR TITLE
Implement parallel build downloads

### PR DESCRIPTION
**Pull request by ichina**
This pull request implements parallel build downloads for Android and iOS builds. Previously, the downloads were done sequentially, which could lead to slower download times. With this change, the downloads are done concurrently, improving overall build performance.

Screenshot 2024-04-27 at 5 48 40 PM
PS: the progress bar on the pic is just for demonstration purposes of parallel downloads, its not a part of this PR

### CODE REVIEW

**Comment by ichina** [comment]
@rams23 please check it out

**Review by rams23 — APPROVED** [review]

**Comment by rams23** [comment]
> @rams23 please check it out 

Hi @ichina ,thank you for the PR! It's great to see that someone is using rnbh! :D I'm away from my PC this week, i Will create a new release in the next one

**Comment by ichina** [comment]
@rams23 ping)

**Comment by rams23** [comment]
> @rams23 ping)

released in v0.10.2

**Pull request merged**
